CREATE TABLE CALENDER(
    DATE DATE
);

CREATE TABLE CUSTOMERS(
    CUSTOMERKEY SERIAL PRIMARY KEY,
    PREFIX VARCHAR(5),
    FIRSTNAME VARCHAR(50),
    LASTNAME VARCHAR(50),
    BIRTHDATE DATE,
    MARITALSTATUS VARCHAR(2),
    GENDER VARCHAR(2),
    EMAILADDRESS VARCHAR(100),
    ANNUALLNCOME FLOAT,
    TOTALCHILDREN INT,
    EDUCATIONLEVEL VARCHAR(50),
    OCCUPATION VARCHAR(50),
    HOMEOWNER VARCHAR(2)
);

CREATE TABLE SALES(
    ORDERNUMBER VARCHAR(10),
    ORDERDATE DATE,
    STOCKDATE DATE,
    ORDERLINEITEM INT,
    ORDERQUANTITY INT,
    PRODUCTKEY INT NOT NULL,
    CUSTOMERKEY INT NOT NULL,
    TERRITORYKEY INT NOT NULL
);

CREATE TABLE TERRITORIES(
    SALESTERRITORYKEY SERIAL PRIMARY KEY,
    REGION VARCHAR(50),
    COUNTRY VARCHAR(50),
    CONTINENT VARCHAR(50)
);

CREATE TABLE RETURNS(
    RETURNDATE DATE,
    RETURNQUANTITY INT,
    PRODUCTKEY INT NOT NULL,
    TERRITORYKEY INT NOT NULL
);

CREATE TABLE PRODUCTS(
    PRODUCTKEY SERIAL PRIMARY KEY,
    PRODUCTSKU VARCHAR(50),
    PRODUCTNAME VARCHAR(100),
    MODELNAME VARCHAR(50),
    PRODUCTDESCRIPTION VARCHAR(500),
    PRODUCTCOLOR VARCHAR(50),
    PRODUCTSIZE VARCHAR(2),
    PRODUCTSTYLE VARCHAR(2),
    PRODUCTCOST FLOAT,
    PRODUCTPRICE FLOAT,
    PRODUCTSUBCATEGORYKEY INT NOT NULL
);

CREATE TABLE PRODUCTS_SUBCATEGORIES(
    PRODUCTSUBCATEGORYKEY SERIAL PRIMARY KEY,
    SUBCATEGORYNAME VARCHAR(50),
    PRODUCTCATEGORYKEY INT NOT NULL
);

CREATE TABLE PRODUCTS_CATEGORIES(
    PRODUCTCATEGORYKEY SERIAL PRIMARY KEY,
    CATEGORYNAME VARCHAR(50)
);


ALTER TABLE SALES
ADD CONSTRAINT SALES_PRODUCT_FK FOREIGN KEY (PRODUCTKEY)
REFERENCES PRODUCTS (PRODUCTKEY);

ALTER TABLE SALES
ADD CONSTRAINT SALES_CUSTOMER_FK FOREIGN KEY (CUSTOMERKEY)
REFERENCES CUSTOMERS (CUSTOMERKEY);

ALTER TABLE SALES
ADD CONSTRAINT SALES_TERRITORY_FK FOREIGN KEY (TERRITORYKEY)
REFERENCES TERRITORIES (SALESTERRITORYKEY);

ALTER TABLE RETURNS
ADD CONSTRAINT RETURNS_PRODUCTS_FK FOREIGN KEY (PRODUCTKEY)
REFERENCES PRODUCTS (PRODUCTKEY);

ALTER TABLE RETURNS
ADD CONSTRAINT RETURNS_TERRITORIES_FK FOREIGN KEY (TERRITORYKEY)
REFERENCES TERRITORIES (SALESTERRITORYKEY);

ALTER TABLE PRODUCTS
ADD CONSTRAINT PRODUCTS_PRODUCTSUBCATEGORIES_FK FOREIGN KEY (PRODUCTSUBCATEGORYKEY)
REFERENCES PRODUCTS_SUBCATEGORIES (PRODUCTSUBCATEGORYKEY);

ALTER TABLE PRODUCTS_SUBCATEGORIES
ADD CONSTRAINT PRODUCTSUBCATEGORIES_PRODUCTCATEGORIES_FK FOREIGN KEY (PRODUCTCATEGORYKEY)
REFERENCES PRODUCTS_CATEGORIES (PRODUCTCATEGORYKEY);
